<a href="https://colab.research.google.com/github/Manish927/Algorithm/blob/patch1/NumpyMatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creating an empty  Numpy array

In [1]:
import numpy as np


In [ ]:
empty_array = np.array(object = [])
empty_array # by default the data type is float

array([], dtype=float64)

In [ ]:
type(empty_array)

numpy.ndarray

In [ ]:
my_array = np.array(object = [1,2,3,4,5])
my_array
my_array.dtype
my_array.shape
my_array.size
my_array.ndim

1

In [ ]:
my_array = np.array(object = [1.5, 2, 4]) # will be converted to float
my_array

array([1. , 2.5, 4. ])

In [ ]:
my_array = np.array(object = ['yes', 'no', 'maybe'])
my_array

array(['yes', 'no', 'maybe'], dtype='<U5')

In [ ]:
my_array = np.arange(start = 1, stop = 20, step = 2)   # more ways to create array
my_array

my_array = np.array(range(1, 20, 2))
my_array

my_array = np.zeros(shape = 10, dtype = int)
my_array

my_array = np.ones(shape = 10, dtype = int)
my_array

my_array = np.full(shape = 10, fill_value = 5)
my_array

my_array = np.linspace(start = 2, stop = 3, num = 5)
my_array

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

# Create Multi Dimensional NumPy arrays

In [4]:
matrix = np.array(object = [[1,2,3], [4,5,6], [7,8,9]])
matrix
matrix.shape

threeDArray = np.array(object = [[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])
threeDArray

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

# Creating Indexing and Slicing in NumPy Array

In [ ]:
my_array = np.array(object= [1,2,3,4,5])
my_array = np.arange(start = 1, stop = 20, step = 2)

my_array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
my_array[0]   # first element
my_array[-1]  # last element

np.int64(19)

In [ ]:
my_array[1:4] # slicing

array([3, 5, 7])

In [ ]:
my_array[1:6:2] # slicing with step

array([ 3,  7, 11])

In [ ]:
my_array > 9 # boolean indexing

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
my_array[my_array > 9] # boolean indexing

array([11, 13, 15, 17, 19])

In [ ]:
# Fancy indexing
my_array[[1,3,5]]

array([ 3,  7, 11])

In [ ]:
# get the indices where the elements within an array meet the conditions
indices = np.where(my_array > 9, 100, my_array)   # (condition, case if met, else): does not modify the original array in place
indices

array([  1,   3,   5,   7,   9, 100, 100, 100, 100, 100])

In [ ]:
# Shallow copy
my_array_copy = my_array
my_array_copy

#deep copy
my_array_copy = my_array.copy()
my_array_copy

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
# Slicing multi-dimensional array
matrix = np.array(object = [[1,2,3], [4,5,6], [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matrix[1][2]  # both are same
matrix[1,2]

np.int64(6)

In [ ]:
# slicing
matrix[0:2, 0:2]

matrix[:3, 2:]

array([[3],
       [6],
       [9]])

In [5]:
threeDArray = np.array(object = [[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]], [[18, 19, 20,], [21, 22, 23], [24,25,26]]])
threeDArray

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
threeDArray[1,2,1]  # both are same
threeDArray[1][2][1]

np.int64(17)

In [ ]:
#slicing
threeDArray[0:2, 0:2, 0:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [ ]:
threeDArray[threeDArray < 12]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

How to extract the element at the first layer of depth, in second row, and in the third column

In [ ]:
threeDArray[0, 1, 2]

np.int64(6)

In [ ]:
# slice to find the elements at the first two levels of depth, in the first two rows, and in the first two columns
threeDArray[0:2, 0:2, 0:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

Integer indexing to index elements at (0,0,0), (1,1,1) and (2,2,2)

In [6]:
threeDArray[[0,1,2],[0,1,2], [0,1,2]]    #, getting data from first dimension, second dimension, third dimension

array([ 1, 14, 26])

In [7]:
threeDArray > 15  # doing boolean

array([[[False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]])

In [8]:
threeDArray[threeDArray > 15]

array([16, 17, 18, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [10]:
# if we don't want to collapse the indexing
np.where(threeDArray > 15, threeDArray, np.nan)

array([[[nan, nan, nan],
        [nan, nan, nan],
        [nan, nan, nan]],

       [[nan, nan, nan],
        [nan, nan, nan],
        [16., 17., 18.]],

       [[18., 19., 20.],
        [21., 22., 23.],
        [24., 25., 26.]]])

In [11]:
# if we provide only the condition to np.where, we will retrieve the indices where the condition is met
np.where(threeDArray > 15)

(array([1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 array([2, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2]),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]))