<a href="https://colab.research.google.com/github/Manish927/Algorithm/blob/patch1/NumPy_Advance_Reshaping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Let's imagine we are give some data being output by a weather vane for every day of the year. Let's imagine that each data point is recording temperatures at different times during the day, for the purpose of this experiment, the actual data is irrelevant. Let's use the np.random.uniform() function to create random, uniformly distributed data withing a range of resonable temperatures.


In [3]:
data = np.random.uniform(low=0, high=40, size=(365, 5)) # size (365, 5) means 655 days and 5 features, or reading from 5 different device
data

array([[30.03129416,  5.83867236, 17.26290727, 21.08380033, 14.55565898],
       [25.78128386,  4.67938845, 36.97488796,  7.1885716 , 25.73897233],
       [16.67913498,  7.7127462 ,  6.17710841, 37.38165362, 38.1777529 ],
       ...,
       [11.23790885,  3.21430924, 15.54170306, 25.21345504, 21.91536879],
       [30.80003245,  8.89546615,  6.52247996,  7.43196358, 34.44282776],
       [ 6.98799467, 32.53354072, 17.01077334, 25.22882845, 18.08223011]])

In [ ]:
# The ValueError: cannot reshape array of size 1825 into shape (7,5) occurs because the total number of elements in your 'data' array (365 days * 5 features = 1825 elements)
# is not evenly divisible by the product of the last two dimensions of the target shape (7 days * 5 features = 35 elements).
# When data.reshape(-1, 7, 5) is called, numpy tries to calculate the first dimension ('-1') by dividing the total number of elements (1825) by the product of the other dimensions (7 * 5 = 35).
# Since 1825 is not perfectly divisible by 35 (1825 / 35 = 52.14...), numpy cannot create a new shape with an integer number of "weeks", leading to the ValueError.
# This issue arises because a year (365 days) is not perfectly divisible by 7 (days in a week).

# To fix this, we can truncate the data to a number of days that is perfectly divisible by 7, for example, 364 days (52 weeks).
# we want ot view our data on a weekly basis instead. How can we reshape this data to achieve this transformation
weekly_data = data[:364].reshape(-1, 7, 5) # Truncate to 364 days (52 weeks)
weekly_data

In [7]:
weekly_data.shape

(52, 7, 5)

In [11]:
# another way to do this is by padding dat with some zeros
rows_needed = 7 - (data.shape[0] % 7)   # calculating how many rows are needed to fill up the last week
new_length = data.shape[0] + rows_needed  # new length after adding the padding
padded_data = np.pad(data, ((0, rows_needed), (0, 0)), mode='constant')
reshaped_data = padded_data.reshape(-1, 7, 5)
reshaped_data.shape

(53, 7, 5)

In [14]:
# weekly data
weekly_data = reshaped_data.reshape(-1, 7, 5)
weekly_data[1]

array([[39.64643234, 17.68063392, 32.49867915, 24.91742342, 19.15467394],
       [12.11499153,  9.56708037, 30.66342182, 14.45112454, 22.04252702],
       [31.27749591, 29.07183381, 22.90457774, 14.74656965, 28.03894416],
       [21.02652241, 17.33967089, 13.17372347, 13.56417515,  7.28682603],
       [30.18995913,  5.97522403,  1.48281757, 12.27792037, 35.51413992],
       [29.95456694, 21.10988038, 18.24965978, 21.4292867 , 12.35753433],
       [ 7.38589139,  3.47021004, 25.93439151, 28.64148168, 17.8470198 ]])

In [15]:
weekly_data[-1]

array([[ 6.98799467, 32.53354072, 17.01077334, 25.22882845, 18.08223011],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]])

In [18]:
# fouteeth week, on Tuesday(day with index 1) and for the fifth weather measurement
weekly_data[13][1][4]

np.float64(28.5515675867924)